<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ecommerce-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\eCommerce.AuthenticationApi\src\AuthenticationApi.Api\AuthenticationApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.GatewayApi\src\GatewayApi.Api\GatewayApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.NotificationApi\src\NotificationApi.Api\NotificationApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.OrderApi\src\OrderApi.Api\OrderApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.PaymentApi\src\PaymentApi.Api\PaymentApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.ProductApi\src\ProductApi.Api\ProductApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.UserApi\src\UserApi.Api\UserApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.ImageApi\src\ImageApi.Api\ImageApi.Api.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.MessagingApi\src\MessagingApi.Api\MessagingApi.Api.csproj" />
  </ItemGroup>

</Project>
