<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AuthenticationApi.Domain\AuthenticationApi.Domain.csproj" />
    <ProjectReference Include="..\AuthenticationApi.Messages\AuthenticationApi.Messages.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.NotificationApi\src\NotificationApi.Messages\NotificationApi.Messages.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.SharedLibrary\SharedLibrary.Application\SharedLibrary.Application.csproj" />
    <ProjectReference Include="..\..\..\eCommerce.UserApi\src\UserApi.Messages\UserApi.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.4.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
