using Aspire.Hosting.ApplicationModel;
using eCommerce.AppHost.Configuration;

namespace eCommerce.AppHost.Extensions;

/// <summary>Contains shared infrastructure resources and service databases.</summary>
public sealed record InfrastructureResources(
    IResourceBuilder<PostgresServerResource> Postgres,
    IResourceBuilder<PostgresDatabaseResource> ProductDb,
    IResourceBuilder<PostgresDatabaseResource> OrderDb,
    IResourceBuilder<PostgresDatabaseResource> PaymentDb,
    IResourceBuilder<PostgresDatabaseResource> UserDb,
    IResourceBuilder<PostgresDatabaseResource> ImageDb,
    IResourceBuilder<PostgresDatabaseResource> AuthenticationDb,
    IResourceBuilder<PostgresDatabaseResource> NotificationDb,
    IResourceBuilder<PostgresDatabaseResource> MessagingDb,
    IResourceBuilder<PostgresDatabaseResource> SellerDb,
    IResourceBuilder<ContainerResource> PgAdmin,
    IResourceBuilder<RabbitMQServerResource> RabbitMq,
    IResourceBuilder<ContainerResource> Minio,
    IResourceBuilder<ContainerResource> Keycloak,
    IResourceBuilder<ContainerResource> Seq,
    IResourceBuilder<ContainerResource> Redis,
    IResourceBuilder<ContainerResource> Mailpit);

/// <summary>Adds shared local infrastructure resources.</summary>
public static class InfrastructureResourceExtensions
{
    /// <summary>Adds databases, brokers, storage, identity, logging, caching, and development tools.</summary>
    public static InfrastructureResources AddInfrastructureResources(
        this IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings)
    {
        // PostgreSQL is shared infrastructure, but each microservice gets a separate logical database.
        // The 18.x image stores cluster data under version-specific subdirectories, so the named volume
        // should be treated as tied to this major version unless a pg_upgrade flow is performed.
        var postgres = ConfigurePostgresServer(
            builder,
            parameters,
            settings,
            out var productDb,
            out var orderDb,
            out var paymentDb,
            out var userDb,
            out var imageDb,
            out var authenticationDb,
            out var notificationDb,
            out var messagingDb,
            out var sellerDb);

        var pgAdmin = ConfigurePgAdmin(builder, parameters, settings, postgres);

        // RabbitMQ backs service-to-service request/response messaging through MassTransit. Explicit local
        // credentials prevent accidental default guest mismatches and keep connection strings generated by
        // Aspire aligned with the service appsettings.
        var rabbitMq = ConfigureRabbitMq(builder, parameters, settings);

        // MinIO is configured with two endpoints: "api" for S3-compatible object operations and "console"
        // for browser administration. ImageApi waits for this resource before starting.
        var minio = ConfigureMinio(builder, parameters, settings);

        // Keycloak uses start-dev for local configuration work. The hostname is set to the same public URL
        // that services and browsers use so issuer and discovery URLs remain stable during development.
        var keycloak = ConfigureKeycloak(builder, parameters, settings);

        // Seq requires accepting its EULA. Local authentication is disabled here to keep development logs
        // easy to inspect; production should provide an admin password or equivalent secure setup.
        var seq = ConfigureSeq(builder, settings);

        // Redis is intentionally lightweight local infrastructure: append-only persistence keeps cache data
        // across restarts for easier inspection, while short application TTLs keep stale read models bounded.
        var redis = ConfigureRedis(builder, settings);

        // Mailpit receives development SMTP messages and keeps them in an inspectable local inbox.
        var mailpit = ConfigureMailpit(builder, settings);

        return new InfrastructureResources(
            postgres,
            productDb,
            orderDb,
            paymentDb,
            userDb,
            imageDb,
            authenticationDb,
            notificationDb,
            messagingDb,
            sellerDb,
            pgAdmin,
            rabbitMq,
            minio,
            keycloak,
            seq,
            redis,
            mailpit);
    }

    private static IResourceBuilder<ContainerResource> ConfigureMailpit(
        IDistributedApplicationBuilder builder,
        AppHostSettings settings)
    {
        var mailpit = builder.AddContainer("mailpit", settings.MailpitImage)
            .WithEndpoint(port: settings.MailpitSmtpPort, targetPort: 1025, name: "smtp")
            .WithHttpEndpoint(port: settings.MailpitUiPort, targetPort: 8025, name: "http");
        return mailpit;
    }

    private static IResourceBuilder<ContainerResource> ConfigureRedis(
        IDistributedApplicationBuilder builder,
        AppHostSettings settings)
    {
        var redis = builder.AddContainer("redis", settings.RedisImage)
            .WithArgs("redis-server", "--appendonly", "yes")
            .WithEndpoint(port: settings.RedisPort, targetPort: 6379, name: "tcp")
            .WithVolume(settings.RedisDataVolume, "/data");
        return redis;
    }

    private static IResourceBuilder<ContainerResource> ConfigureSeq(
        IDistributedApplicationBuilder builder,
        AppHostSettings settings)
    {
        var seq = builder.AddContainer("seq", settings.SeqImage)
            .WithEnvironment("ACCEPT_EULA", "Y")
            .WithEnvironment("SEQ_FIRSTRUN_NOAUTHENTICATION", "true")
            .WithHttpEndpoint(port: settings.SeqPort, targetPort: 80, name: "http")
            .WithVolume(settings.SeqDataVolume, "/data");
        return seq;
    }

    private static IResourceBuilder<ContainerResource> ConfigureKeycloak(
        IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings)
    {
        var keycloak = builder.AddContainer("keycloak", settings.KeycloakImage)
            .WithArgs("start-dev", $"--http-port={settings.KeycloakPort}", $"--hostname={settings.KeycloakHostname}")
            .WithEnvironment("KEYCLOAK_ADMIN", parameters.KeycloakAdminUser)
            .WithEnvironment("KEYCLOAK_ADMIN_PASSWORD", parameters.KeycloakAdminPassword)
            .WithHttpEndpoint(port: settings.KeycloakPort, targetPort: settings.KeycloakPort, name: "http")
            .WithVolume(settings.KeycloakDataVolume, "/opt/keycloak/data");
        return keycloak;
    }

    private static IResourceBuilder<ContainerResource> ConfigureMinio(
        IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings)
    {
        var minio = builder.AddContainer("minio", settings.MinioImage)
            .WithArgs("server", "/data", "--console-address", ":9001")
            .WithEnvironment("MINIO_ROOT_USER", parameters.MinioRootUser)
            .WithEnvironment("MINIO_ROOT_PASSWORD", parameters.MinioRootPassword)
            .WithEndpointProxySupport(false)
            .WithHttpEndpoint(port: settings.MinioApiPort, targetPort: 9000, name: "api")
            .WithHttpEndpoint(port: settings.MinioConsolePort, targetPort: 9001, name: "console")
            .WithVolume(settings.MinioDataVolume, "/data");
        return minio;
    }

    private static IResourceBuilder<RabbitMQServerResource> ConfigureRabbitMq(
        IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings)
    {
        var rabbitMq = builder.AddRabbitMQ("rabbitmq", parameters.RabbitMqUser, parameters.RabbitMqPassword, settings.RabbitMqPort)
            .WithManagementPlugin()
            .WithDataVolume(settings.RabbitMqDataVolume);
        return rabbitMq;
    }

    private static IResourceBuilder<ContainerResource> ConfigurePgAdmin(
        IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings,
        IResourceBuilder<PostgresServerResource> postgres)
    {
        var pgAdmin = builder.AddContainer("pgadmin", settings.PgAdminImage)
            .WithEnvironment("PGADMIN_DEFAULT_EMAIL", parameters.PgAdminEmail)
            .WithEnvironment("PGADMIN_DEFAULT_PASSWORD", parameters.PgAdminPassword)
            .WithEnvironment("PGADMIN_CONFIG_SERVER_MODE", settings.PgAdminServerMode)
            .WithEnvironment("PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED", settings.PgAdminMasterPasswordRequired)
            .WithHttpEndpoint(port: settings.PgAdminPort, targetPort: 80, name: "http")
            .WithBindMount(settings.PgAdminServersPath, "/pgadmin4/servers.json", isReadOnly: true)
            .WithVolume(settings.PgAdminDataVolume, "/var/lib/pgadmin")
            .WaitFor(postgres)
            .WithExternalHttpEndpoints();
        return pgAdmin;
    }

    private static IResourceBuilder<PostgresServerResource> ConfigurePostgresServer(
        IDistributedApplicationBuilder builder,
        AppHostParameters parameters,
        AppHostSettings settings,
        out IResourceBuilder<PostgresDatabaseResource> productDb,
        out IResourceBuilder<PostgresDatabaseResource> orderDb,
        out IResourceBuilder<PostgresDatabaseResource> paymentDb,
        out IResourceBuilder<PostgresDatabaseResource> userDb,
        out IResourceBuilder<PostgresDatabaseResource> imageDb,
        out IResourceBuilder<PostgresDatabaseResource> authenticationDb,
        out IResourceBuilder<PostgresDatabaseResource> notificationDb,
        out IResourceBuilder<PostgresDatabaseResource> messagingDb,
        out IResourceBuilder<PostgresDatabaseResource> sellerDb)
    {
        var postgres = builder.AddPostgres("postgres", parameters.PostgresUser, parameters.PostgresPassword, port: settings.PostgresPort)
            .WithImageTag(settings.PostgresImageTag)
            .WithDataVolume(settings.PostgresDataVolume);

        productDb = postgres.AddDatabase("product-db", settings.ProductDbName);
        orderDb = postgres.AddDatabase("order-db", settings.OrderDbName);
        paymentDb = postgres.AddDatabase("payment-db", settings.PaymentDbName);
        userDb = postgres.AddDatabase("user-db", settings.UserDbName);
        imageDb = postgres.AddDatabase("image-db", settings.ImageDbName);
        authenticationDb = postgres.AddDatabase("authentication-db", settings.AuthenticationDbName);
        notificationDb = postgres.AddDatabase("notification-db", settings.NotificationDbName);
        messagingDb = postgres.AddDatabase("messaging-db", settings.MessagingDbName);
        sellerDb = postgres.AddDatabase("seller-db", settings.SellerDbName);
        return postgres;
    }
}
